### ISSUE TITLE
typo

### ISSUE THREAD

**Issue by jplatts12** [w3f/polkadot-wiki-old#116]
current: "It will be closed to 10% in the first year. Each validator will get 1,000 - 2,000 DOTs per month share with their nominators."

suggested: add "to" before "share"

http://wiki.polkadot.network/en/latest/polkadot/learn/staking/

**Comment by jplatts12** [comment]
current: "The VRF use in Polkadot"

suggested: "The VRF used in Polkadot"

http://wiki.polkadot.network/en/latest/polkadot/learn/randomness/

**Comment by jplatts12** [comment]
Add a period after "There are three different accounts for managing your funds". "These" should be the start of a new sentence. 

http://wiki.polkadot.network/en/latest/polkadot/learn/staking/

**Comment by laboon** [comment]
Should be fixed with https://github.com/w3f/polkadot-wiki/pull/117

**Comment by laboon** [comment]
#117 approved, closing this issue.

Thanks for filing!
