### ISSUE TITLE
Building on Polkadot 

### ISSUE THREAD

**Issue by jplatts12** [w3f/polkadot-wiki-old#119]
"Once you secure your entry into the parachain registry you are guaranteed that spot until either 1) the duration of the time attached to that entry has elapsed or 2) the governance mechanism votes to remove it." - Gavin said in his recent presentations that there is no explicit mechanism to remove parachains for governance. 

http://wiki.polkadot.network/en/latest/polkadot/build/build-with-polkadot/

**Comment by laboon** [comment]
@jplatts12 - Do you have a link to one of those presentations?  (asking for my own edification)

**Comment by laboon** [comment]
Not sure in which commit, but this was fixed sometime this week.
