### ISSUE TITLE
typo

### ISSUE THREAD

**Issue by jplatts12** [w3f/polkadot-wiki-old#120]
current: "when an action will end based on the output we are given."

suggested: "when an auction will end based on the output we are given."

http://wiki.polkadot.network/en/latest/polkadot/learn/candle/

**Comment by lsaether** [comment]
@jplatts12 You are able to suggest changes on the wiki by clicking the pen at the top right of each page under the header. It will take you to the GitHub editor where you will be able to make PRs. That way we can make the changes live by just accepting them
