### ISSUE TITLE
Vote Weighting & Counting Overview

### ISSUE THREAD

**Issue by ansonla3** [w3f/polkadot-wiki-old#13]

**Comment by lsaether** [comment]
@ansonla3 could you comment more details for this?

**Comment by ltfschoen** [comment]
We've got PRs for the Rust documentation that includes both the [Democracy SRML](https://github.com/paritytech/substrate/pull/2286/files) and the Council SRML](https://github.com/paritytech/substrate/pull/2447/files).

We've said that the Democracy SRML was designed to **tally** votes of public referenda in the "Goals" section, and we discuss it further in the "Terminology" section.

The `tally` function tally's the votes for the current proposal. Its documentation comments say that it returns a data structure with weighted votes for, against, and total capital represented in the vote.

Each person that votes on a proposal needs to lock a deposit that matches the deposit made by the creator of the proposal. These are all stored in `DepositOf` (the account ids that voted, and the amount they deposited)

We also **tally** votes in the Council SRML docs

**Comment by ltfschoen** [comment]
it looks like this is ready to be closed, as there are already overviews here for each:
* Vote Weighting - https://wiki.polkadot.network/en/latest/polkadot/learn/governance/#vote-weighting
* Vote Counting - https://wiki.polkadot.network/en/latest/polkadot/learn/governance/#vote-counting

**Comment by lsaether** [comment]
Long has been completed.
