### ISSUE TITLE
Interchain Communication

### ISSUE THREAD

**Issue by lsaether** [w3f/polkadot-wiki-old#19]

**Comment by jplatts12** [comment]
0xThreeBody (PolkadWallet) says there is quite a bit of demand for how interchain message passing works. This would make for a great blog post if we adapt existing materials from wiki.polkadot.network. Is this something tech ed is interested in doing?

**Comment by lsaether** [comment]
@jplatts12  Sure, can put it into the pipeline for early next week. I think the tutorial will not be able to be written until launch of testnet for PoC4 but I think the development is far enough along that I would be able to write more of an explainer on how it will work.
