### ISSUE TITLE
Add "Overview>Ecosystem"

### ISSUE THREAD

**Issue by laboon** [w3f/polkadot-wiki-old#2]
Projects listed here: 
here is AdEx Network in Bulgaria, ChainX and 万企融 in China, Commonwealth, Agoric, C3 and ChainLink in the US, Katallassos in Switzerland, Ocean, EWF and Asure Network in Germany, UniqX in the UK, iExec in France, Blink in Romania and Polkascan in The Netherlands.

**Comment by lsaether** [comment]
We already have the community/ecosystem page which links to the list maintained by @jplatts12  of teams building on polkadot.
