### ISSUE TITLE
make wiki governance same as blog post 

### ISSUE THREAD

**Issue by jplatts12** [w3f/polkadot-wiki-old#245]
Time: The amount of time those tokens will remain locked after the referendum has ended. Five periods are allowed: 4 weeks, 8 weeks, 16 weeks, 32 weeks and 64 weeks. Each doubling of the period results in the voter getting an additional “vote”.

From: https://medium.com/polkadot-network/a-walkthrough-of-polkadots-governance-486555a056e0

Wiki has 6 periods.

**Comment by laboon** [comment]
That's not what the code says - do you know which is right?

https://github.com/paritytech/substrate/blob/master/srml/democracy/src/lib.rs

```rust
pub enum Conviction {
	/// 0.1x votes, unlocked.
	None,
	/// 1x votes, locked for an enactment period following a successful vote.
	Locked1x,
	/// 2x votes, locked for 2x enactment periods following a successful vote.
	Locked2x,
	/// 3x votes, locked for 4x...
	Locked3x,
	/// 4x votes, locked for 8x...
	Locked4x,
	/// 5x votes, locked for 16x...
	Locked5x,
	/// 6x votes, locked for 32x...
	Locked6x,
}
```

**Comment by lsaether** [comment]
I generally don't always agree with the sentiment that "Code is Law." However, whatever is implemented in code is how it works today; without evidence that there is any work intending to change this (such as an open issue or a pull request), the wiki should reflect the current functionality of the system.
