### ISSUE TITLE
Staking

### ISSUE THREAD

**Issue by lsaether** [w3f/polkadot-wiki-old#44]
See [here](https://hackmd.io/s2gQaEqvRXWJJ6-ZpAGyPw) for resources

**Comment by ansonla3** [comment]
staking economics have not finalized yet

**Comment by lsaether** [comment]
Have you seen [this video](https://youtu.be/IRc5Jma_eH8?t=1602) yet?  It talks a little bit about the economics.

**Comment by ansonla3** [comment]
awesome! can start to write a brief overview

**Comment by lsaether** [comment]
What is the status of this one @ansonla3 ?

**Comment by ansonla3** [comment]
@lsaether  ready for review

**Comment by lsaether** [comment]
Long been competed.
