### ISSUE TITLE
More content on comparison with Cosmos / Tendermint

### ISSUE THREAD

**Issue by lsaether** [w3f/polkadot-wiki-old#60]
Will take some content from the recent AMA and do additional research on the comparison between Polkadot and Cosmos since this will likely be a pretty hot topic moving forward.

**Comment by Web3Foundation** [comment]
Would be great to get a community info-graphic cross-comparing main differences.

**Comment by laboon** [comment]
If this issue is done according to the Progress Tracker, should we close it?
