### ISSUE TITLE
Disqus integration

### ISSUE THREAD

**Issue by lsaether** [w3f/polkadot-wiki-old#66]
While browsing through the material docs (to make the page nicer and using all the features available - yay!)  I noticed that there is the possibility for a [disqus integration](https://squidfunk.github.io/mkdocs-material/getting-started/#disqus). Disqus is a plug-in that enables commenting on the the wiki pages. 

This is a nice feature but is it a needed feature? I'm not integrating it into the wiki at this time but if anyone has a strong reason and puts it below I could be persuaded.

**Comment by laboon** [comment]
I'd actually argue against adding this.  It's definitely not a needed feature, and puts the onus on the team to moderate comments (or allow it to descend into a free-for-all).  Disqus can stop generic spam but there may be other kinds of comments added that we don't particularly want there (e.g. requests for help).

If there were a big payoff, I'd be for it, but I don't think there is.  I personally have never found much use for those kinds of comments.

**Comment by lsaether** [comment]
I agree, let's not integrate disqus.
