### ISSUE TITLE
Consensus explainer and comparison

### ISSUE THREAD

**Issue by keorn** [w3f/polkadot-wiki-old#70]

**Comment by lsaether** [comment]
Proposing this outline:

- Why Consensus?
- What is GRANDPA / BABE?
    - GRANDPA
    - What is "Polite GRANDPA"?
    - BABE
- GRANDPA / BABE compared to...
    - PBFT
    - Tendermint
    - HoneyBadgerBFT
    - Casper CBC
    - Avalanche (? optional)

**Comment by keorn** [comment]
looks good, could start with also talking about the tradeoffs for finality: speed vs decentralisation

**Comment by lsaether** [comment]
done
